export const ADD_META_FILES = 'ADD_META_FILES';
export const SET_META_LOADING = 'SET_META_LOADING';
export const ADD_META_TABLE_DATA = 'ADD_META_TABLE_DATA';
export const SET_META_UPLOAD_BUTTON = 'SET_META_UPLOAD_BUTTON';
