const ADD_METAFACTS_FILES = 'ADD_METAFACTS_FILES';
const ADD_METAFACTS_VALIDATIONS = 'ADD_METAFACTS_VALIDATIONS';
const ADD_METAFACTS_EXPECTATIONS = 'ADD_METAFACTS_EXPECTATIONS';
const SET_METAFACTS_UPLOAD_BUTTON = 'SET_METAFACTS_UPLOAD_BUTTON';
const SET_METAFACTS_LOADING = 'SET_METAFACTS_LOADING';
const UPLOADED_METAFACTS_FILES_VALIDITY = 'UPLOADED_METAFACTS_FILES_VALIDITY';

export {
  ADD_METAFACTS_FILES,
  ADD_METAFACTS_VALIDATIONS,
  ADD_METAFACTS_EXPECTATIONS,
  SET_METAFACTS_UPLOAD_BUTTON,
  SET_METAFACTS_LOADING,
  UPLOADED_METAFACTS_FILES_VALIDITY,
};
