export const ADD_FILES = 'ADD_FILES';
export const ADD_VALIDATIONS = 'ADD_VALIDATIONS';
export const ADD_EXPECTATIONS = 'ADD_EXPECTATIONS';
export const SET_UPLOAD_BUTTON = 'SET_UPLOAD_BUTTON';
export const RESET_PANEL_FLAG = 'RESET_PANEL_FLAG';
export const SET_LOADING = 'SET_LOADING';
export const UPLOADED_FILES_VALIDITY = 'UPLOADED_FILES_VALIDITY';
